# Generated by Django 4.2.13 on 2024-05-14 22:52

import authorization.managers
import authorization.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=60, unique=True, validators=[authorization.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'BaseUser',
                'verbose_name_plural': 'BaseUsers',
            },
            managers=[
                ('objects', authorization.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authorization.baseuser')),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
            bases=('authorization.baseuser',),
            managers=[
                ('objects', authorization.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authorization.baseuser')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
            bases=('authorization.baseuser',),
            managers=[
                ('objects', authorization.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authorization.baseuser')),
                ('balance', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=('authorization.baseuser',),
            managers=[
                ('objects', authorization.managers.CustomUserManager()),
            ],
        ),
    ]
