# Generated by Django 4.2.13 on 2024-05-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'Base User', 'verbose_name_plural': 'Base Users'},
        ),
    ]
