# Generated by Django 4.2.13 on 2024-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short',
            field=models.TextField(blank=True),
        ),
    ]
