# Generated by Django 4.2.13 on 2024-05-14 22:52

from django.db import migrations, models
import django.db.models.deletion
import offers.models
import offers.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Offer category',
                'verbose_name_plural': 'Offer categories',
            },
        ),
        migrations.CreateModel(
            name='OfferMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField()),
                ('alt', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('audio', 'Аудио'), ('video', 'Видео'), ('file', 'Файл'), ('license', 'Лицензия'), ('other', 'Другое')], default='other', max_length=20)),
            ],
            options={
                'verbose_name': 'Offer media',
                'verbose_name_plural': 'Offer medias',
            },
        ),
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Offer type',
                'verbose_name_plural': 'Offer types',
            },
        ),
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=68, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('exp_date', models.DateTimeField(default=offers.utils.set_token_exp_date)),
            ],
            options={
                'verbose_name': 'Secret',
                'verbose_name_plural': 'Secrets',
            },
        ),
        migrations.CreateModel(
            name='TargetAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Target action',
                'verbose_name_plural': 'Target actions',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('about', models.TextField()),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner', to='offers.secretkey')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=offers.models.offer_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('reward_from', models.IntegerField(blank=True)),
                ('reward_to', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField()),
                ('source_url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='offers.offercategory')),
                ('medias', models.ManyToManyField(related_name='offer', to='offers.offermedia')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offers.partner')),
                ('target_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.targetaction')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offertype')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
