# Generated by Django 4.2.13 on 2024-05-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_partner_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='offer', to='offers.offermedia'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='reward_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='reward_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
